### ISSUE TITLE
Install package qemu-user-static

### ISSUE THREAD

**Issue by smuda** [smuda/home-cluster-argo#14]
This is to support running multi arch builds

**Comment by smuda** [comment]
Example:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: qemu-user-static-master
spec:
  config:
    ignition:
      version: 3.2.0
  extensions:
    - qemu-user-static
```
